### ISSUE TITLE
[stream-quality-filter] customize filters (e.g only 4k and 1080p)

### ISSUE THREAD

**Issue by tkiterio** [sleeyax/stremio-addons#1]
hi, 
 2 suggestation to improve the addon stream filter on app directily or web browser.
1-make the addon personalized sort stream from hd to 4k.. or  peers or size or select the trackers like torrentio addon
2-make visible the select quality i want, exemple my pc not run 4k movies, i want list only 720p and 1080p, or only 720p.
thanks your addon is the best i only use that

sorry for english

**Comment by sleeyax** [comment]
Yes, quite a few people have requested features like that. I will work on it when I have more free time. Thanks for the suggestion!

**Comment by sleeyax** [comment]
I'm going to split this issue in multiple parts.

**Comment by sleeyax** [comment]
You can now customize filters (e.g only 1080p and 4K) in ae8d52205292ef14fda52c737c5494acc0c353af and 8589ecd19ad52566f47852c948c8ee8afef0adc6. You can also enter your own filter value and sort them in a custom order. Changes will be deployed to the server in a few minutes.
